name: Heads
description: A Minecraft Plugin that gives you a players head.
version: '${project.version}'

author: Flashbang Hosting
website: https://fb-hosting.net/

main: net.fbhosting.heads.HeadsPlugin
api-version: 1.19

depend:
  - LuckPerms

commands:
  head:
    description: Teleport to the specified farming world.
    usage: /<command> [player]

permissions:
  heads.*:
    description: Gives full access to the plugin.
    default: op
    children:
      heads.spawn: true
      heads.bypass: true
      heads.group.*: true
  heads.spawn:
    description: Gives you a Players Head.
    default: true
  heads.bypass:
    description: Bypasses the heads timeout.
    default: op
  heads.group.*:
    description: Allows you to get the head of a player in this group.
    default: true
